- id: black
  name: black
  description:
    "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
  entry: black
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python]

- id: isort
  name: isort
  description: "Run 'isort' for proper import formatting"
  entry: isort
  language: python
  types_or: [python]
  profile: 'black'

