site_name: EXAUQ-Toolbox

# Settings for deploying as local files, using the file:// scheme
site_url: ""
site_dir: exauq/docs
use_directory_urls: false
plugins:
  - offline
  - gen-files:
      scripts:
      - "scripts/gen_ref_pages.py"
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: list
  - mkdocs-jupyter:
      execute: false  # TODO: change to true for production
      allow_errors: false

nav:
  - Home: "index.md"
  - "Experimental Design":
    - "designers/index.md"
    - "Tutorials":
      - "designers/tutorials/index.md"
      - "Training a Gaussian Process Emulator": "designers/tutorials/training_gp_tutorial.ipynb"
      - "Training a Multi-Level Gaussian Process Emulator": "designers/tutorials/training_multi_level_gp_tutorial.ipynb"
      - "Single Level Adaptive Sampling": "designers/tutorials/slas_tutorial.ipynb"
  - "Command Line App":
    - "cli/index.md"
    - "A First Walkthrough": "cli/first-walkthrough.md"
    - "User Guides":
      - "cli/user-guides/index.md"
      - "Writing a Simulator Script": "cli/user-guides/simulator-script.md"
      - "Getting Information on Jobs": "cli/user-guides/showing-jobs.md"
      - "Cancelling Jobs": "cli/user-guides/cancelling-jobs.md"
      - "Resubmitting Jobs": "cli/user-guides/resubmitting-jobs.md"
  - "API Reference": "api/"

# Material for MkDocs
theme:
  name: material
  features:
    - navigation.sections  # navigation pane, see https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.indexes
    - content.code.annotate  # code annotations, see https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations

# See:
# - https://squidfunk.github.io/mkdocs-material/reference/admonitions/
# - https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
# - https://squidfunk.github.io/mkdocs-material/reference/grids/
# - https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
# - https://squidfunk.github.io/mkdocs-material/reference/math/#katex
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

# For KaTeX to render maths, see
# https://squidfunk.github.io/mkdocs-material/reference/math/#katex
extra_javascript:
- javascripts/katex.js
- https://unpkg.com/katex@0/dist/katex.min.js
- https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css