[tool.poetry]
authors = ["Exeter RSE Group"]
description = "A toolbox for doing uncertainty quantification at the exascale"
name = "exauq"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.group.dev.dependencies]
black = ">=22.0.0"
mogp-emulator = "^0.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
