name: Documentation Upload
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Configure Git credentials
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Step 3: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      # Step 4: Cache Poetry dependencies
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # Step 5: Install Poetry
      - name: Install Poetry
        run: pipx install poetry

      # Step 6: Install dependencies with Poetry
      - name: Install dependencies
        run: poetry install --with=dev

      # Step 7: Build Jupyter notebooks
      - name: Build Jupyter notebooks
        run: |
          set -e
          set -x
          poetry run python scripts/build_notebooks.py

      # Step 8: Build MkDocs site
      - name: Build MkDocs
        run: |
          set -e
          set -x
          poetry run mkdocs build

    #   # Step 9: Deploy to GitHub Pages
    #   - name: Deploy to GitHub Pages
    #     run: |
    #       set -e
    #       set -x
    #       poetry run mkdocs gh-deploy --force

