# These are PR checks that with protected branch rules will not allow
# for pushes or merging of PRs without checks passing. Theoretically, if one
# uses the pre-commit hooks - they shouldn't fail. 

name: Test linting
run-name: "Test linting upon ${{ github.event_name }} from ${{ github.ref_name }}"
on:
  pull_request:
    branches: [ "dev", "main", "release/*" ]
  push:
    branches: [ "dev", "main", "release/*" ]
  repository_dispatch:
  workflow_dispatch:
  workflow_call:

jobs:
  black:
    name: Black formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install black
        run: pipx install black
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
      - name: Run black
        run: black --check --line-length 90 .

  isort:
    name: Isort import sorting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install isort
        run: pipx install isort
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
      - name: Run isort
        run: isort --check-only .
