# These are PR checks that with protected branch rules will not allow
# for pushes or merging of PRs without checks passing. Theoretically, if one
# uses the pre-commit hooks - they shouldn't fail. 

name: Test linting
run-name: "Test linting upon ${{ github.event_name }} from ${{ github.ref_name }}"
on:
  pull_request_review:
    types: [submitted]
  repository_dispatch:
  workflow_dispatch:
  workflow_call:

jobs:
  black:
    if: ${{ github.event.review.state == 'approved' && 
          (github.event.pull_request.base.ref == 'main' || 
            github.event.pull_request.base.ref == 'dev' || 
            startsWith(github.event.pull_request.base.ref, 'releases/')) 
            }}
    name: Black formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install black
        run: pipx install black
      - name: Run black
        run: black --check --line-length 90 .

  isort:
    if: ${{ github.event.review.state == 'approved' && 
          (github.event.pull_request.base.ref == 'main' || 
            github.event.pull_request.base.ref == 'dev' || 
            startsWith(github.event.pull_request.base.ref, 'releases/')) 
            }}
    name: Isort import sorting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install isort
        run: pipx install isort
      - name: Run isort
        run: isort --check-only .
