# This workflow will install EXAUQ-Toolbox, with dependencies, and run unit
# tests. For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test python package
run-name: "Test Python package upon ${{ github.event_name }} from ${{ github.ref_name }}"
on:
  push:
    branches: [ "dev", "main", "release/*" ]
  repository_dispatch:
  workflow_dispatch:
  workflow_call:

jobs:
  job1:
    name: Run unittest tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"
    - name: Install dependencies
      run: poetry install --with=dev
    - name: Run unit tests
      run: poetry run python -m unittest discover tests/
