# This workflow will install EXAUQ-Toolbox, with dependencies, and run unit
# tests. For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test python package
run-name: "Test Python package upon ${{ github.event_name }} from ${{ github.ref_name }}"
on:
  push:
    branches: [ "dev", "main", "release/*" ]
  repository_dispatch:
  workflow_dispatch:
env:
  POETRY_HOME: "/opt/poetry"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      # Cf. 'Using pip (aka manually)' section of:
      # https://python-poetry.org/docs/#ci-recommendations   
      run: |
        python3 -m venv ${{ env.POETRY_HOME }}
        ${{ env.POETRY_HOME }}/bin/pip install poetry
        echo "Installed $(${{ env.POETRY_HOME }}/bin/poetry --version)"
    - name: Install dependencies
      run: ${{ env.POETRY_HOME }}/bin/poetry install --with=dev
    - name: Run unit tests
      run: ${{ env.POETRY_HOME }}/bin/poetry run python -m unittest discover tests/
